# Generated by Django 5.1.3 on 2024-11-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('plan', '0007_remove_itinerary_locations_itinerary_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='plan.review'),
        ),
    ]
