# Generated by Django 5.1.3 on 2024-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_location_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
