# Generated by Django 5.1.3 on 2024-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
