# Generated by Django 5.1.3 on 2024-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='num_visits',
            field=models.IntegerField(default=0),
        ),
    ]
