# Generated by Django 5.1.3 on 2024-11-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_id',
            field=models.CharField(max_length=100),
        ),
    ]
